# <font color='black'><center><center></font> 
![title](img/All.png) 
# <font color='white'><center><center></font> 
# <font><center>Neural Networks & Deep Learning<center></font>
# <font ><center>HW4: Q2<center></font>
## <center>Teacher: Dr. Kalhor<center>
### <center>Mohammadali Shakerdargah <center>
### <center>810196487<center>

In [12]:
import numpy as np
import math
import copy

In [2]:
m = 6
eps = 0.13
W = np.zeros((m,m))
W = W + np.eye(m)
for row in W:
    for i in range(len(row)):
        if(row[i] != 1):
            row[i] = (-1)*eps
print("Weight:\n",W)

Weight:
 [[ 1.   -0.13 -0.13 -0.13 -0.13 -0.13]
 [-0.13  1.   -0.13 -0.13 -0.13 -0.13]
 [-0.13 -0.13  1.   -0.13 -0.13 -0.13]
 [-0.13 -0.13 -0.13  1.   -0.13 -0.13]
 [-0.13 -0.13 -0.13 -0.13  1.   -0.13]
 [-0.13 -0.13 -0.13 -0.13 -0.13  1.  ]]


# MaxNet 

In [3]:
def activation_function(x):
    res = []
    for i in range(len(x)):
        res.append(max(x[i],0))
    return res

In [4]:
def find_num_nonzero_elements(x):
    cnt = 0
    for i in range(len(x)):
        if(x[i] != 0):
            cnt +=1
    return cnt

In [14]:
def find_nonzero_element_index(x):
    num = 0
    for i in range(len(x)):
        if(x[i] != 0):
            num = i
            break
    return num

## Part A:

In [22]:
stop_onlyOneNodePositive = False
a_old = [1.2, 1.1, 0.5, 1.5, 1.13, 0.8]
print("iteration = ", 0, "\n  Res: ", a_old, "\n")
    
iteration = 1
maxOfBothCon = [0, 0, 0, 0, 0, 0]
while(stop_onlyOneNodePositive == False):
    a_new = activation_function(W @ a_old)
    print("iteration = ", iteration, "\n  Res: ", a_new, "\n")
    if(find_num_nonzero_elements(a_new) == 1):
        maxOfBothCon.append(find_nonzero_element(a_new))
        stop_onlyOneNodePositive = True
    a_old = a_new
    iteration += 1


iteration =  0 
  Res:  [1.2, 1.1, 0.5, 1.5, 1.13, 0.8] 

iteration =  1 
  Res:  [0.5460999999999999, 0.43310000000000004, 0, 0.8851, 0.46699999999999986, 0.09410000000000002] 

iteration =  2 
  Res:  [0.3017909999999999, 0.1741010000000001, 0, 0.684861, 0.21240799999999985, 0] 

iteration =  3 
  Res:  [0.16251289999999993, 0.018223200000000106, 0, 0.5953820000000001, 0.06151010999999984, 0] 

iteration =  4 
  Res:  [0.07474790969999995, 0, 0, 0.5638899927000001, 0, 0] 

iteration =  5 
  Res:  [0.0014422106489999365, 0, 0, 0.5541727644390001, 0, 0] 

iteration =  6 
  Res:  [0, 0, 0, 0.5539852770546301, 0, 0] 



## Part B:

In [21]:
stop_con1, stop_con2, stop_conFinal  = False, False, False
a_old = [1.2, 1.1, 0.5, -1.5, 1.13, -0.8]
a_old_org = copy.deepcopy(a_old)
toBeMultiplied = -1
a_old_neg = []
for num in a_old:
    a_old_neg.append(num * toBeMultiplied)
a_old_neg_org = copy.deepcopy(a_old_neg)
maxOfBothCon = [0, 0, 0, 0, 0, 0]

print('.......................  First Part ............................')
print("iteration = ", 0, "\n  Res: ", a_old, "\n")
iteration = 1
while(stop_con1 == False):
    a_new = activation_function(W @ a_old)
    print("iteration = ", iteration, "\n  Res: ", a_new, "\n")
    if(find_num_nonzero_elements(a_new) == 1):
        indexOfLargest = find_nonzero_element_index(a_new)
        maxOfBothCon[indexOfLargest] = a_old_org[indexOfLargest]
        stop_con1 = True
    a_old = a_new
    iteration += 1


print('.......................  Second Part ............................')
print("iteration = ", 0, "\n  Res: ", a_old_neg, "\n")
iteration = 1
while(stop_con2 == False):
    a_neg_new = activation_function(W @ a_old_neg)
    print("iteration = ", iteration, "\n  Res: ", a_neg_new, "\n")
    if(find_num_nonzero_elements(a_neg_new) == 1):
        indexOfLargest = find_nonzero_element_index(a_neg_new)
        maxOfBothCon[indexOfLargest] = a_old_neg_org[indexOfLargest]
        stop_con2 = True
    a_old_neg = a_neg_new
    iteration += 1
    
print('.......................... Final Part ............................')
print("iteration = ", 0, "\n  Res: ", maxOfBothCon, "\n")
iteration = 1
while(stop_conFinal == False):
    maxOfBothCon_new = activation_function(W @ maxOfBothCon)
    print("iteration = ", iteration, "\n  Res: ", maxOfBothCon_new, "\n")
    if(find_num_nonzero_elements(maxOfBothCon_new) == 1):
        stop_conFinal = True
    maxOfBothCon = a_neg_new
    iteration += 1

.......................  First Part ............................
iteration =  0 
  Res:  [1.2, 1.1, 0.5, -1.5, 1.13, -0.8] 

iteration =  1 
  Res:  [1.1441, 1.0311000000000003, 0.3531000000000001, 0, 1.065, 0] 

iteration =  2 
  Res:  [0.8257039999999999, 0.6980140000000004, 0, 0, 0.7363209999999999, 0] 

iteration =  3 
  Res:  [0.6392404499999998, 0.4949507500000004, 0, 0, 0.5382376599999998, 0] 

iteration =  4 
  Res:  [0.5049259566999998, 0.34187859570000045, 0, 0, 0.39079280399999977, 0] 

iteration =  5 
  Res:  [0.40967867473899977, 0.2254351568090005, 0, 0, 0.28070821218799974, 0] 

iteration =  6 
  Res:  [0.3438800367693897, 0.13568486150849057, 0, 0, 0.1981434140867597, 0] 

iteration =  7 
  Res:  [0.3004823609420072, 0.06522181289719114, 0, 0, 0.13579997731063526, 0] 

iteration =  8 
  Res:  [0.2743495282149898, 0.008505108924347624, 0, 0, 0.08825843471153946, 0] 

iteration =  9 
  Res:  [0.2617702675423245, 0, 0, 0, 0.051487331883425594, 0] 

iteration =  10 
  Res: 