# <font color='black'><center><center></font> 
![title](img/All.png) 
# <font color='white'><center><center></font> 
# <font><center>Neural Networks & Deep Learning<center></font>
# <font ><center>HW3: Q4<center></font>
## <center>Teacher: Dr. Kalhor<center>
### <center>Mohammadali Shakerdargah <center>
### <center>810196487<center>

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import random
import copy
import statistics

In [3]:
class BAMNN:
    def __init__(self, _S, _T):
        self.S = _S
        self.T = _T
        self.W = np.zeros((len(_S[1]), len(_T[1])))
        
    def train(self):
        for trainSample in range(len(self.S)):
            x = self.S[trainSample]
            y = self.T[trainSample]
            for i in range(len(x)):
                for j in range(len(y)):
                    self.W[i][j] = self.W[i][j] + x[i]*y[j]
    def giveWeight(self):
        return (self.W)
    
    def showResultWithOutNoise(self, _S_space, _T_space): # n% of values with noise
        T_space = copy.deepcopy(_T_space)
        rightAns = False
        res = False
        S_space = copy.deepcopy(_S_space)
        Y_t_list = []
        
        while(rightAns != True):
            for sample in range(len(S_space)):
                
#                 y_t_sample = []
#                 for i in range(len()):
#                     y_i_new = 0
#                     for j in range(len()):
#                         y_i_new += S_space[sample][j]*self.W[j][i]
#                     y_t_sample.append(y_i_new)
#//
                y_t_sample = np.dot(self.W, np.transpose(S_space[sample]))
#
                for i in range(len(y_t_sample)): #sign
                    if(y_t_sample[i] > 0):
                        y_t_sample[i] = 1
                    elif(y_t_sample[i] < 0):
                        y_t_sample[i] = -1
                Y_t_list.append(y_t_sample)
                
#                 for i in range(len(self.W)):
#                     x_i_new = 0
#                     for j in range(len(self.W[0])):
#                         x_i_new += self.W[i][j]*Y_t_list[sample][j]
#                     S_space[sample][i] = x_i_new
#//
                S_space[sample] = np.dot(np.transpose(Y_t_list[sample]), (self.W))
                for i in range(len(S_space[sample])):
                    if(S_space[sample][i] > 0):
                        S_space[sample][i] = 1
                    elif(S_space[sample][i] < 0):
                        S_space[sample][i] = -1
                        
            Y_t_array = np.array(Y_t_list)
            if(np.array_equal(Y_t_array, _T_space)): 
                rightAns = True
        print("Desired output:\n",_T_space)
        print("Network's output:\n", Y_t_array)
        if(rightAns):
            res = "\n => Converged to desired output"
        return res

In [4]:
A_s = [[-1, 1, -1],
      [1, -1, 1],
      [1, 1, 1],
      [1, -1, 1],
      [1, -1, 1]]
B_s = [[1, 1, -1],
      [1, -1, 1],
      [1, 1, -1],
      [1, -1, 1],
      [1, 1, -1]]
C_s = [[-1, 1, 1],
      [1, -1, -1],
      [1, -1, -1],
      [1, -1, -1],
      [-1, 1, 1]]
D_s = [[1, 1, -1],
      [1, -1, 1],
      [1, -1, 1],
      [1, -1, 1],
      [1, 1, -1]]
E_s = [[1, 1, 1],
      [1, -1, -1],
      [1, 1, -1],
      [1, -1, -1],
      [1, 1, 1]]
F_s = [[1, 1, 1],
      [1, -1, -1],
      [1, 1, -1],
      [1, -1, -1],
      [1, -1, -1]]
G_s = [[-1, 1, 1],
      [1, -1, -1],
      [1, -1, 1],
      [1, -1, 1],
      [-1, 1, 1]]
H_s = [[1, -1, 1],
      [1, -1, 1],
      [1, 1, 1],
      [1, -1, 1],
      [1, -1, 1]]

A_s = np.array(A_s)
B_s = np.array(B_s)
C_s = np.array(C_s)
D_s = np.array(D_s)
E_s = np.array(E_s)
F_s = np.array(F_s)
G_s = np.array(G_s)
H_s = np.array(H_s)

A_t = np.array([-1,-1,-1])
B_t = np.array([-1,-1, 1])
C_t = np.array([-1, 1,-1])
D_t = np.array([-1, 1, 1])
E_t = np.array([ 1,-1,-1])
F_t = np.array([ 1,-1, 1])
G_t = np.array([ 1, 1,-1])
H_t = np.array([ 1, 1, 1])

A_s_reshaped = A_s.reshape((A_s.shape[0]*A_s.shape[1]))
B_s_reshaped = B_s.reshape((B_s.shape[0]*B_s.shape[1]))
C_s_reshaped = C_s.reshape((C_s.shape[0]*C_s.shape[1]))
D_s_reshaped = D_s.reshape((D_s.shape[0]*D_s.shape[1]))
E_s_reshaped = E_s.reshape((E_s.shape[0]*E_s.shape[1]))
F_s_reshaped = F_s.reshape((F_s.shape[0]*F_s.shape[1]))
G_s_reshaped = G_s.reshape((G_s.shape[0]*G_s.shape[1]))
H_s_reshaped = H_s.reshape((H_s.shape[0]*H_s.shape[1]))


# Part A

In [5]:
S = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped)])
T = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t)])
bam = BAMNN(S, T)
bam.train()
W = bam.giveWeight()
print(W)


[[ 1. -1.  3.]
 [-3. -1. -1.]
 [ 1.  3. -1.]
 [-3. -1. -1.]
 [ 3.  1.  1.]
 [-1. -3.  1.]
 [-3. -1. -1.]
 [-1. -3.  1.]
 [ 1. -1. -1.]
 [-3. -1. -1.]
 [ 3.  1.  1.]
 [-1. -3.  1.]
 [-1. -3.  1.]
 [-1.  1.  1.]
 [-1.  1. -3.]]


# Part B

In [6]:
_S_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped)])
_T_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t)])
T_space = copy.deepcopy(_T_space)
rightAns = False
res = False
S_space = copy.deepcopy(_S_space)
Y_t_list = []

while(rightAns != True):
    for sample in range(len(S_space)):
        
        y_t_sample = []
        for i in range(len(W[0])):
            y_i_new = 0
            for j in range(len(W)):
                y_i_new += S_space[sample][j]*W[j][i]
            y_t_sample.append(y_i_new)
        for i in range(len(y_t_sample)): #sign
            if(y_t_sample[i] > 0):
                y_t_sample[i] = 1
            elif(y_t_sample[i] < 0):
                y_t_sample[i] = -1
        Y_t_list.append(y_t_sample)

        for i in range(len(W)):
            x_i_new = 0
            for j in range(len(W[0])):
                x_i_new += W[i][j]*Y_t_list[sample][j]
            S_space[sample][i] = x_i_new
        for i in range(len(S_space[sample])):
            if(S_space[sample][i] > 0):
                S_space[sample][i] = 1
            elif(S_space[sample][i] < 0):
                S_space[sample][i] = -1

    Y_t_array = np.array(Y_t_list)
    if(np.array_equal(Y_t_array, _T_space)): 
        rightAns = True
print("Input given to Network\n", _S_space)
print("Desired output:\n",_T_space)
print("Network's output:\n", Y_t_array)
if(rightAns):
    res = "\n => Converged to desired output"
print(res)

Input given to Network
 [[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
 [ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1 -1]
 [-1  1  1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1]]
Desired output:
 [[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]]
Network's output:
 [[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]]

 => Converged to desired output


In [7]:
_T_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped)])
_S_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t)])
T_space = copy.deepcopy(_T_space)
rightAns = False
res = False
S_space = copy.deepcopy(_S_space)
Y_t_list = []

while(rightAns != True):
    for sample in range(len(S_space)):
        
        y_t_sample = []
        y_t_sample = np.dot(W, np.transpose(S_space[sample]))
        for i in range(len(y_t_sample)): #sign
            if(y_t_sample[i] > 0):
                y_t_sample[i] = 1
            elif(y_t_sample[i] < 0):
                y_t_sample[i] = -1
        Y_t_list.append(y_t_sample)

        S_space[sample] = np.dot(np.transpose(Y_t_list[sample]), (W))
        for i in range(len(S_space[sample])):
            if(S_space[sample][i] > 0):
                S_space[sample][i] = 1
            elif(S_space[sample][i] < 0):
                S_space[sample][i] = -1

    Y_t_array = np.array(Y_t_list)
    if(np.array_equal(Y_t_array, _T_space)): 
        rightAns = True
print("Input given to Network\n", _S_space)
print("Desired output:\n",_T_space)
print("Network's output:\n", Y_t_array)
if(rightAns):
    res = "\n => Converged to desired output"
print(res)

Input given to Network
 [[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]]
Desired output:
 [[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
 [ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1 -1]
 [-1  1  1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1]]
Network's output:
 [[-1.  1. -1.  1. -1.  1.  1.  1.  1.  1. -1.  1.  1. -1.  1.]
 [ 1.  1. -1.  1. -1.  1.  1.  1. -1.  1. -1.  1.  1.  1. -1.]
 [-1.  1.  1.  1. -1. -1.  1. -1. -1.  1. -1. -1. -1.  1.  1.]]

 => Converged to desired output


# Part C 10% noise

In [24]:
_S_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped)])
_T_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t)])
n = 10
numTrue = 0
for i in range(100):
    T_space = copy.deepcopy(_T_space)
    S_space = copy.deepcopy(_S_space)
    rightAns = False
    res = False
    k = 0
    for sample in range(len(S_space)):
        toNoise = int(len(S_space[0])*(n/100))
        randomIndexes = random.sample(range(1, len(S_space[0])-1), toNoise)
        for index in randomIndexes:
            if(S_space[sample][index] == 1):
                S_space[sample][index] = -1
            else:
                S_space[sample][index] = 1
    
    while((rightAns == False) and (k<1000)):
        Y_t_list = []
        for sample in range(len(S_space)):
            
            y_t_sample = []
            for i in range(len(W[0])):
                y_i_new = 0
                for j in range(len(W)):
                    y_i_new += S_space[sample][j]*W[j][i]
                y_t_sample.append(y_i_new)
            for i in range(len(y_t_sample)): #sign
                if(y_t_sample[i] > 0):
                    y_t_sample[i] = 1
                elif(y_t_sample[i] < 0):
                    y_t_sample[i] = -1
            Y_t_list.append(y_t_sample)

            for i in range(len(W)):
                x_i_new = 0
                for j in range(len(W[0])):
                    x_i_new += W[i][j]*Y_t_list[sample][j]
                S_space[sample][i] = x_i_new
            for i in range(len(S_space[sample])):
                if(S_space[sample][i] > 0):
                    S_space[sample][i] = 1
                elif(S_space[sample][i] < 0):
                    S_space[sample][i] = -1
        k += 1
        Y_t_array = np.array(Y_t_list)
        if(np.array_equal(Y_t_array, _T_space)): 
            rightAns = True
            numTrue += 1

In [28]:
cnt = 0
for i in range(len(Y_t_array)):
    for j in range(len(Y_t_array[0])):
        if(Y_t_array[i][j] == _T_space[i][j]):
            cnt += 1
print("Correct detected pixels: ",(cnt*100)/(len(Y_t_array) * len(Y_t_array[0])),"%")
print("accuracy: ",numTrue, "%")

Correct detected pixels:  100.0 %
accuracy:  100 %


In [31]:
_S_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped)])
_T_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t)])
n = 40
numTrue = 0
for i in range(100):
    T_space = copy.deepcopy(_T_space)
    S_space = copy.deepcopy(_S_space)
    rightAns = False
    res = False
    k = 0
    for sample in range(len(S_space)):
        toNoise = int(len(S_space[0])*(n/100))
        randomIndexes = random.sample(range(1, len(S_space[0])-1), toNoise)
        for index in randomIndexes:
            if(S_space[sample][index] == 1):
                S_space[sample][index] = -1
            else:
                S_space[sample][index] = 1
    
    while((rightAns == False) and (k<10000)):
        Y_t_list = []
        for sample in range(len(S_space)):
            
            y_t_sample = []
            for i in range(len(W[0])):
                y_i_new = 0
                for j in range(len(W)):
                    y_i_new += S_space[sample][j]*W[j][i]
                y_t_sample.append(y_i_new)
            for i in range(len(y_t_sample)): #sign
                if(y_t_sample[i] > 0):
                    y_t_sample[i] = 1
                elif(y_t_sample[i] < 0):
                    y_t_sample[i] = -1
            Y_t_list.append(y_t_sample)

            for i in range(len(W)):
                x_i_new = 0
                for j in range(len(W[0])):
                    x_i_new += W[i][j]*Y_t_list[sample][j]
                S_space[sample][i] = x_i_new
            for i in range(len(S_space[sample])):
                if(S_space[sample][i] > 0):
                    S_space[sample][i] = 1
                elif(S_space[sample][i] < 0):
                    S_space[sample][i] = -1
        k += 1
        Y_t_array = np.array(Y_t_list)
        if(np.array_equal(Y_t_array, _T_space)): 
            rightAns = True
            numTrue += 1

In [32]:
cnt = 0
for i in range(len(Y_t_array)):
    for j in range(len(Y_t_array[0])):
        if(Y_t_array[i][j] == _T_space[i][j]):
            cnt += 1
print("Correct detected pixels: ",cnt/(len(Y_t_array) * len(Y_t_array[0])))
print("accuracy: ",numTrue, "%")

Correct detected pixels:  0.7777777777777778
accuracy:  5 %


# Part D

In [ ]:
_T_space = np.array([copy.deepcopy(A_s_reshaped)])
_S_space = np.array([[0, -1, -1]])
T_space = copy.deepcopy(_T_space)
rightAns = False
res = False
S_space = copy.deepcopy(_S_space)
Y_t_list = []

while(rightAns != True):
    for sample in range(len(S_space)):
        
        y_t_sample = []
        y_t_sample = np.dot(W, np.transpose(S_space[sample]))
        for i in range(len(y_t_sample)): #sign
            if(y_t_sample[i] > 0):
                y_t_sample[i] = 1
            elif(y_t_sample[i] < 0):
                y_t_sample[i] = -1
        Y_t_list.append(y_t_sample)

        S_space[sample] = np.dot(np.transpose(Y_t_list[sample]), (W))
        for i in range(len(S_space[sample])):
            if(S_space[sample][i] > 0):
                S_space[sample][i] = 1
            elif(S_space[sample][i] < 0):
                S_space[sample][i] = -1

    Y_t_array = np.array(Y_t_list)
    if(np.array_equal(Y_t_array, _T_space)): 
        rightAns = True
print("Input given to Network\n", _S_space)
print("Desired output:\n",_T_space)
print("Network's output:\n", Y_t_array)
if(rightAns):
    res = "\n => Converged to desired output"
print(res)

# Part E

In [61]:
S = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped),
             copy.deepcopy(D_s_reshaped), copy.deepcopy(E_s_reshaped), copy.deepcopy(F_s_reshaped),
             copy.deepcopy(G_s_reshaped), copy.deepcopy(H_s_reshaped)])
T = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t),
             copy.deepcopy(D_t), copy.deepcopy(E_t), copy.deepcopy(F_t),
             copy.deepcopy(G_t), copy.deepcopy(H_t)])
bam = BAMNN(S, T)
bam.train()
W = bam.giveWeight()
print(W)

[[ 2. -2.  6.]
 [-2. -2. -2.]
 [ 6.  2. -2.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [-4.  0.  4.]
 [ 0.  0.  0.]
 [ 2. -6.  2.]
 [ 0.  4.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [-2.  2.  2.]
 [ 0. -4.  4.]
 [-2.  2. -2.]
 [ 2.  2. -6.]]


# Part F: All 8 data recognition

In [62]:
# _S_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped)])
# _T_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t)])

_S_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped),
             copy.deepcopy(D_s_reshaped), copy.deepcopy(E_s_reshaped), copy.deepcopy(F_s_reshaped),
             copy.deepcopy(G_s_reshaped), copy.deepcopy(H_s_reshaped)])
_T_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t),
             copy.deepcopy(D_t), copy.deepcopy(E_t), copy.deepcopy(F_t),
             copy.deepcopy(G_t), copy.deepcopy(H_t)])

T_space = copy.deepcopy(_T_space)
rightAns = False
res = False
S_space = copy.deepcopy(_S_space)
Y_t_list = []
k=0
while(rightAns != True and (k<4000)):
    Y_t_list = []
    for sample in range(len(S_space)):
        
        y_t_sample = []
        for i in range(len(W[0])):
            y_i_new = 0
            for j in range(len(W)):
                y_i_new += S_space[sample][j]*W[j][i]
            y_t_sample.append(y_i_new)
        for i in range(len(y_t_sample)): #sign
            if(y_t_sample[i] > 0):
                y_t_sample[i] = 1
            elif(y_t_sample[i] < 0):
                y_t_sample[i] = -1
        Y_t_list.append(y_t_sample)

        for i in range(len(W)):
            x_i_new = 0
            for j in range(len(W[0])):
                x_i_new += W[i][j]*Y_t_list[sample][j]
            S_space[sample][i] = x_i_new
        for i in range(len(S_space[sample])):
            if(S_space[sample][i] > 0):
                S_space[sample][i] = 1
            elif(S_space[sample][i] < 0):
                S_space[sample][i] = -1
    k+=1
    Y_t_array = np.array(Y_t_list)
    if(np.array_equal(Y_t_array, _T_space)): 
        rightAns = True
print("Input given to Network\n", _S_space)
print("Desired output:\n",_T_space)
print("Network's output:\n", Y_t_array)
if(rightAns):
    res = "\n => Converged to desired output"
else:
    res = "\n => Divergent"
cnt = 0
for i in range(len(Y_t_array)):
    for j in range(len(Y_t_array[0])):
        if(Y_t_array[i][j] == _T_space[i][j]):
            cnt += 1
print("Correct detected pixels: ",cnt/(len(Y_t_array) * len(Y_t_array[0])))
print(res)

Input given to Network
 [[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
 [ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1 -1]
 [-1  1  1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1]
 [ 1  1 -1  1 -1  1  1 -1  1  1 -1  1  1  1 -1]
 [ 1  1  1  1 -1 -1  1  1 -1  1 -1 -1  1  1  1]
 [ 1  1  1  1 -1 -1  1  1 -1  1 -1 -1  1 -1 -1]
 [-1  1  1  1 -1 -1  1 -1  1  1 -1  1 -1  1  1]
 [ 1 -1  1  1 -1  1  1  1  1  1 -1  1  1 -1  1]]
Desired output:
 [[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]
 [-1  1  1]
 [ 1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]
 [ 1  1  1]]
Network's output:
 [[-1 -1  1]
 [-1 -1  1]
 [ 1  1 -1]
 [-1  1  1]
 [ 1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]
 [ 1 -1  1]]
Correct detected pixels:  0.875

 => Divergent


# Part F: 4 data recognition

In [63]:
S = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped),
             copy.deepcopy(G_s_reshaped)])
T = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t),
             copy.deepcopy(G_t)])
bam = BAMNN(S, T)
bam.train()
W = bam.giveWeight()
print(W)

[[ 0. -2.  4.]
 [-2.  0. -2.]
 [ 2.  4. -2.]
 [-2.  0. -2.]
 [ 2.  0.  2.]
 [-2. -4.  2.]
 [-2.  0. -2.]
 [-2. -4.  2.]
 [ 2.  0. -2.]
 [-2.  0. -2.]
 [ 2.  0.  2.]
 [ 0. -2.  0.]
 [-2. -4.  2.]
 [ 0.  2.  0.]
 [ 0.  2. -4.]]


In [65]:
# _S_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped)])
# _T_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t)])

_S_space = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped),
             copy.deepcopy(G_s_reshaped)])
_T_space = np.array([copy.deepcopy(A_t), copy.deepcopy(B_t), copy.deepcopy(C_t),
             copy.deepcopy(G_t)])

T_space = copy.deepcopy(_T_space)
rightAns = False
res = False
S_space = copy.deepcopy(_S_space)
Y_t_list = []
k=0
while(rightAns != True and (k<4000)):
    Y_t_list = []
    for sample in range(len(S_space)):
        
        y_t_sample = []
        for i in range(len(W[0])):
            y_i_new = 0
            for j in range(len(W)):
                y_i_new += S_space[sample][j]*W[j][i]
            y_t_sample.append(y_i_new)
        for i in range(len(y_t_sample)): #sign
            if(y_t_sample[i] > 0):
                y_t_sample[i] = 1
            elif(y_t_sample[i] < 0):
                y_t_sample[i] = -1
        Y_t_list.append(y_t_sample)

        for i in range(len(W)):
            x_i_new = 0
            for j in range(len(W[0])):
                x_i_new += W[i][j]*Y_t_list[sample][j]
            S_space[sample][i] = x_i_new
        for i in range(len(S_space[sample])):
            if(S_space[sample][i] > 0):
                S_space[sample][i] = 1
            elif(S_space[sample][i] < 0):
                S_space[sample][i] = -1
    k+=1
    Y_t_array = np.array(Y_t_list)
    if(np.array_equal(Y_t_array, _T_space)): 
        rightAns = True
print("Input given to Network\n", _S_space)
print("Desired output:\n",_T_space)
print("Network's output:\n", Y_t_array)
if(rightAns):
    res = "\n => Converged to desired output"
else:
    res = "\n => Divergent"
cnt = 0
for i in range(len(Y_t_array)):
    for j in range(len(Y_t_array[0])):
        if(Y_t_array[i][j] == _T_space[i][j]):
            cnt += 1
print("Correct detected pixels: ",cnt/(len(Y_t_array) * len(Y_t_array[0])))
print(res)

Input given to Network
 [[-1  1 -1  1 -1  1  1  1  1  1 -1  1  1 -1  1]
 [ 1  1 -1  1 -1  1  1  1 -1  1 -1  1  1  1 -1]
 [-1  1  1  1 -1 -1  1 -1 -1  1 -1 -1 -1  1  1]
 [-1  1  1  1 -1 -1  1 -1  1  1 -1  1 -1  1  1]]
Desired output:
 [[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]
 [ 1  1 -1]]
Network's output:
 [[-1 -1 -1]
 [-1 -1  1]
 [-1  1 -1]
 [-1  1 -1]]
Correct detected pixels:  0.9166666666666666

 => Divergent


# Part G:


In [ ]:
S = np.array([copy.deepcopy(A_s_reshaped), copy.deepcopy(B_s_reshaped), copy.deepcopy(C_s_reshaped),
             copy.deepcopy(D_s_reshaped), copy.deepcopy(E_s_reshaped), copy.deepcopy(F_s_reshaped),
             copy.deepcopy(G_s_reshaped), copy.deepcopy(H_s_reshaped)])
char_cnt = 1
hamming_dist = []
for char1 in S:
    hamming_dist_char_i = []
    for char2 in S:
        cnt = 0
        for i in range(len(char1)):
            if(char1[i] != char2[i]):
                cnt += 1
        hamming_dist_char_i.append(cnt)
    hamming_dist.append(hamming_dist_char_i)
    char_cnt += 1
for i in range(len(hamming_dist)):
    print(hamming_dist[i])